# render.yaml
services:
  - type: web
    name: quiz-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        description: Telegram bot token
      - key: MONGODB_URI
        description: MongoDB connection URI
      - key: OWNER_ID
        description: Your Telegram user ID
      - key: BOT_USERNAME
        description: Your bot's username (without @)
    healthCheckPath: /health
