services:
  - type: web
    name: quiz-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        fromGroup: telegram
      - key: OWNER_ID
        fromGroup: telegram
      - key: MONGODB_URI
        fromGroup: mongo
      - key: BOT_USERNAME
        fromGroup: telegram
      - key: PORT
        value: 10000
    healthCheckPath: /health
    plan: starter
